"""Standardized error logging service for comprehensive Railway log aggregation.

This service provides a consistent error logging interface for all pipeline
components, ensuring Railway logs are queryable and correlation IDs enable
distributed tracing.

Integration:
- Story 6.1: Uses error_classifier to determine is_transient
- Story 6.3: Includes checkpoint progress in error logs
- Story 6.4: Uses ErrorPayload structure for consistency with Notion sync

Architecture Compliance:
- Uses structlog with JSON output (Railway compatibility)
- Correlation IDs for distributed tracing (Architecture Decision 11)
- Short transaction pattern (never hold DB during logging)

Story Reference: 6.5 - Detailed Error Logging
"""

import structlog
from uuid import UUID
from datetime import datetime, timezone
from typing import Any
from sqlalchemy.ext.asyncio import AsyncSession

from app.services.error_classifier import classify_error, ErrorContext, ErrorCategory
from app.schemas.error_payload import FailureLocation
from app.services.checkpoint_service import get_step_checkpoint

# Configure structlog if not already configured (safe for multiple imports)
# In production, this should be configured once at app startup, but this ensures
# tests and standalone usage work correctly
if not structlog.is_configured():
    structlog.configure(
        processors=[
            structlog.stdlib.filter_by_level,
            structlog.stdlib.add_logger_name,
            structlog.stdlib.add_log_level,
            structlog.stdlib.PositionalArgumentsFormatter(),
            structlog.processors.TimeStamper(fmt="iso"),  # ISO 8601 timestamps
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,  # Full stack traces for ERROR level
            structlog.processors.UnicodeDecoder(),
            structlog.processors.JSONRenderer(),  # Railway-compatible JSON
        ],
        wrapper_class=structlog.stdlib.BoundLogger,
        logger_factory=structlog.stdlib.LoggerFactory(),
        cache_logger_on_first_use=True,
    )

log = structlog.get_logger()


async def log_structured_error(
    exception: Exception,
    task_id: UUID,
    channel_id: str,
    correlation_id: UUID,
    step_name: str,
    retry_attempt: int,
    db: AsyncSession,
    context: ErrorContext | None = None,
) -> None:
    """Log error with comprehensive structure for Railway aggregation.

    Args:
        exception: The exception that occurred
        task_id: UUID of the task that failed
        channel_id: Channel ID for filtering
        correlation_id: Correlation ID for distributed tracing (pass task.id)
        step_name: Pipeline step that failed (e.g., "video_generation")
        retry_attempt: Current retry attempt (1-3)
        db: Database session for checkpoint query
        context: Optional ErrorContext for location-specific details

    Logged Fields:
        - event: "pipeline_step_failed"
        - timestamp: ISO 8601 (auto-generated by structlog)
        - task_id: UUID (str)
        - channel_id: str
        - correlation_id: UUID (str) - same as task_id for distributed tracing
        - step_name: str
        - error_type: Exception class name
        - error_message: Human-readable error description
        - retry_attempt: int (1-3)
        - is_transient: bool (from Story 6.1 classifier)
        - error_category: str (TRANSIENT, PERMANENT, etc.)
        - api_service: str (KIE.ai, Gemini, ElevenLabs, etc.)
        - partial_progress: dict (from Story 6.3 checkpoints)
        - failure_location: str (from Story 6.4 ErrorPayload)
        - exc_info: Full stack trace (ERROR level only)

    Architecture Note:
        correlation_id uses task.id for distributed tracing across retries and steps.
        Task model uses task.id as the correlation identifier (no separate field).
    """
    # Step 1: Classify error (from Story 6.1)
    error_analysis = classify_error(exception, context)
    is_transient = error_analysis.category == ErrorCategory.TRANSIENT

    # Step 2: Query checkpoint progress (from Story 6.3)
    try:
        checkpoint = await get_step_checkpoint(str(task_id), step_name, db)
        partial_progress = checkpoint.get("outputs", {}) if checkpoint else {}
    except Exception as checkpoint_error:
        # If checkpoint query fails, log the issue but continue with empty progress
        # This prevents checkpoint retrieval failures from blocking error logging
        log.warning(
            "checkpoint_query_failed",
            task_id=str(task_id),
            step_name=step_name,
            checkpoint_error=str(checkpoint_error),
            message="Failed to retrieve checkpoint progress for error log",
        )
        partial_progress = {}

    # Step 3: Format failure location (from Story 6.4)
    if context:
        failure_location = FailureLocation(
            step_name=context.step_name,
            item_index=context.clip_index or context.asset_index,
            total_items=context.total_clips or context.total_assets,
            item_name=context.asset_name,
        )
        location_str = failure_location.format()
    else:
        location_str = step_name.replace("_", " ").title()

    # Step 4: Log to Railway with full context
    log.error(
        "pipeline_step_failed",
        task_id=str(task_id),
        channel_id=channel_id,
        correlation_id=str(correlation_id),
        step_name=step_name,
        error_type=exception.__class__.__name__,
        error_message=str(exception),
        retry_attempt=retry_attempt,
        is_transient=is_transient,
        error_category=error_analysis.category.value,
        api_service=error_analysis.api_service or "Unknown",
        failure_location=location_str,
        partial_progress=partial_progress,
        suggested_action=error_analysis.suggested_action,
        confidence=error_analysis.confidence,
        exc_info=True,  # Full stack trace for Railway
    )


async def log_retry_scheduled(
    task_id: UUID,
    correlation_id: UUID,
    retry_attempt: int,
    next_retry_at: datetime,
    retry_delay_seconds: int,
) -> None:
    """Log when retry is scheduled (from Story 6.2 integration).

    Args:
        task_id: UUID of the task being retried
        correlation_id: Correlation ID for distributed tracing
        retry_attempt: Retry attempt number (1-3)
        next_retry_at: Timestamp when retry will be attempted
        retry_delay_seconds: Delay in seconds before retry
    """
    log.warning(
        "task_retry_scheduled",
        task_id=str(task_id),
        correlation_id=str(correlation_id),
        retry_attempt=retry_attempt,
        next_retry_at=next_retry_at.isoformat(),
        retry_delay_seconds=retry_delay_seconds,
    )


async def log_retry_claimed(
    task_id: UUID,
    correlation_id: UUID,
    retry_attempt: int,
    worker_id: str,
) -> None:
    """Log when retry task is claimed by worker (from Story 6.2 integration).

    Args:
        task_id: UUID of the task being claimed
        correlation_id: Correlation ID for distributed tracing
        retry_attempt: Retry attempt number (1-3)
        worker_id: Worker process identifier
    """
    log.info(
        "task_retry_claimed",
        task_id=str(task_id),
        correlation_id=str(correlation_id),
        retry_attempt=retry_attempt,
        worker_id=worker_id,
    )


async def log_terminal_failure(
    task_id: UUID,
    correlation_id: UUID,
    channel_id: str,
    retry_attempts: int,
    final_error_type: str,
    final_error_message: str,
) -> None:
    """Log when max retries are exhausted (terminal failure).

    Args:
        task_id: UUID of the failed task
        correlation_id: Correlation ID for distributed tracing
        channel_id: Channel ID for filtering
        retry_attempts: Total number of retry attempts made
        final_error_type: Exception class name from last failure
        final_error_message: Error message from last failure
    """
    log.critical(
        "task_terminal_failure",
        task_id=str(task_id),
        correlation_id=str(correlation_id),
        channel_id=channel_id,
        retry_attempts=retry_attempts,
        final_error_type=final_error_type,
        final_error_message=final_error_message,
        message=f"Task {task_id} failed permanently after {retry_attempts} retry attempts",
    )


async def log_pipeline_step_started(
    task_id: UUID,
    correlation_id: UUID,
    channel_id: str,
    step_name: str,
) -> None:
    """Log when pipeline step starts.

    Args:
        task_id: UUID of the task
        correlation_id: Correlation ID for distributed tracing
        channel_id: Channel ID for filtering
        step_name: Pipeline step name (e.g., "asset_generation")
    """
    log.info(
        "pipeline_step_started",
        task_id=str(task_id),
        correlation_id=str(correlation_id),
        channel_id=channel_id,
        step_name=step_name,
        timestamp=datetime.now(timezone.utc).isoformat(),
    )


async def log_pipeline_step_completed(
    task_id: UUID,
    correlation_id: UUID,
    channel_id: str,
    step_name: str,
    duration_seconds: float,
) -> None:
    """Log when pipeline step completes successfully.

    Args:
        task_id: UUID of the task
        correlation_id: Correlation ID for distributed tracing
        channel_id: Channel ID for filtering
        step_name: Pipeline step name (e.g., "asset_generation")
        duration_seconds: Step execution time in seconds
    """
    log.info(
        "pipeline_step_completed",
        task_id=str(task_id),
        correlation_id=str(correlation_id),
        channel_id=channel_id,
        step_name=step_name,
        duration_seconds=duration_seconds,
        timestamp=datetime.now(timezone.utc).isoformat(),
    )
